#!/bin/bash

N=$1
IMAGE_NAME=${2:-'map-reduce:server'}
RAISE_CONTAINER='./scripts/raise_container'


echo 'Killing living containers...'
'./scripts/kill_all' $IMAGE_NAME

echo 'Building image...'
docker build ./ -t $IMAGE_NAME

echo 'Starting containers...'
for k in $(seq 1 $N); do
    echo "Raising container $k of $N..."
    $RAISE_CONTAINER $(($k+1)) &
    if [ "$k" -eq "1" ]; then
        sleep 5
    fi
done

sleep 5

# Ignore kill. Kill containers after usage.
trap './scripts/kill_all' EXIT

# Tail containers' outputs.
'./scripts/tail_all'