#!/bin/bash
IP="172.18.0.$1"
CONTAINER_NAME="map-reduce_$IP"
# ..._$(date +%H%M%S_%N)

# docker build ./ -t map-reduce:server
docker run -itd --rm --network=distributed --ip=$IP --name=$CONTAINER_NAME \
       map-reduce:server python main.py
# docker cp . $CONTAINER_NAME:/app/
# docker exec -it $CONTAINER_NAME python main.py
# docker attach $CONTAINER_NAME