#!/bin/bash

TEST=${1:-dht}
CONTAINER_NAME="map-reduce.tester"

# Run the container.
docker run -itd --rm --network=distributed --ip=172.18.0.253 --name=$CONTAINER_NAME \
       map-reduce:server python -m unittest -v "map_reduce.tests.$TEST"

# Tail the logs.
docker logs -f --tail=15 $CONTAINER_NAME

# Kill the container.
cleanup() {
    docker kill $CONTAINER_NAME
}
trap cleanup EXIT